"""esquema inicial

Revision ID: c77264fce60c
Revises: 
Create Date: 2026-06-11 19:09:41.612969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c77264fce60c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=256), nullable=False),
    sa.Column('tipo_evento', sa.String(length=64), nullable=False),
    sa.Column('lugar_publicacion', sa.String(length=128), nullable=False),
    sa.Column('url_articulo', sa.String(length=512), nullable=False),
    sa.Column('year_publicacion', sa.Integer(), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_year_publicacion'), ['year_publicacion'], unique=False)

    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('article_author',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.CheckConstraint('orden >= 1', name='ck_author_order_positive'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'author_id'),
    sa.UniqueConstraint('article_id', 'author_id', name='uq_article_author'),
    sa.UniqueConstraint('article_id', 'orden', name='uq_article_author_order')
    )
    op.create_table('article_corresponding',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'author_id'),
    sa.UniqueConstraint('article_id', 'author_id', name='uq_article_corresponding')
    )
    op.create_table('ejecucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algoritmo', sa.String(length=30), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tiempo_ejecucion_seg', sa.Float(), nullable=False),
    sa.Column('iteraciones', sa.Integer(), nullable=False),
    sa.Column('n_criterios', sa.Integer(), nullable=False),
    sa.Column('n_alternativas', sa.Integer(), nullable=False),
    sa.Column('gbf_final', sa.Float(), nullable=True),
    sa.Column('mejor_alternativa_final', sa.Integer(), nullable=True),
    sa.Column('parametros', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('matriz_entrada', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resultados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('historico_gbf', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('historiales', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.CheckConstraint('iteraciones >= 1', name='ck_ejecucion_iteraciones'),
    sa.CheckConstraint('n_alternativas >= 1', name='ck_ejecucion_n_alternativas'),
    sa.CheckConstraint('n_criterios >= 1', name='ck_ejecucion_n_criterios'),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ejecucion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ejecucion_algoritmo'), ['algoritmo'], unique=False)
        batch_op.create_index('ix_ejecucion_algoritmo_fecha', ['algoritmo', 'fecha_ejecucion'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejecucion_fecha_ejecucion'), ['fecha_ejecucion'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejecucion_fk_user'), ['fk_user'], unique=False)
        batch_op.create_index('ix_ejecucion_user_algoritmo', ['fk_user', 'algoritmo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejecucion', schema=None) as batch_op:
        batch_op.drop_index('ix_ejecucion_user_algoritmo')
        batch_op.drop_index(batch_op.f('ix_ejecucion_fk_user'))
        batch_op.drop_index(batch_op.f('ix_ejecucion_fecha_ejecucion'))
        batch_op.drop_index('ix_ejecucion_algoritmo_fecha')
        batch_op.drop_index(batch_op.f('ix_ejecucion_algoritmo'))

    op.drop_table('ejecucion')
    op.drop_table('article_corresponding')
    op.drop_table('article_author')
    op.drop_table('user')
    op.drop_table('author')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_year_publicacion'))

    op.drop_table('article')
    # ### end Alembic commands ###
